### ISSUE TITLE
where are human anntation?

### ISSUE THREAD

**Issue by alaalial** [saltudelft/many-types-4-py-dataset#5]
Hello, I try to use the tool and predict the types on this dataset but I need the human annotation, where are  human annotation in the data set? you didnot upload file about ground truth, could you please upload it
Thank you

**Comment by mir-am** [comment]
Thanks for using the ManyTypes4Py dataset.
Regarding type annotations, I should point out:
- For variables, there are both human-provided type annotations and Pyre's, and no hint/label is provided to differentiate between the two in the dataset.
- For functions' parameters and return values, all the type annotations are human provided.

------------
Also, if you can't find type annotations, check out this [file](https://github.com/saltudelft/libsa4py/blob/master/JSONOutput.md) for info about the JSON files and their fields in the dataset.
